apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: nginx  #like tag
  ports:
    - protocol: TCP
      port: 8002     #host port
      targetPort: 8000
      nodePort: 31033